[package]
name = "bidirectional_typeinference"
version = "0.1.0"
authors = ["Jakob Demler <jdemler@curry-software.com>"]
edition = "2018"

[dependencies]
im-rc = { version = "15.0.0" }
bitset = {path = "bitset/"}
